/**
 * Catalogue d'exercices FFF — données initiales (seed).
 *
 * Ces exercices couvrent les principaux sous-thèmes de la taxonomie FFF
 * et peuvent être importés en base Firestore via le script de seed.
 *
 * Pour importer des exercices depuis unecatef.fr ou une autre source,
 * ajouter les fiches dans ce tableau en respectant le type ExerciceCatalogue.
 */

import type { ExerciceCatalogue } from './types';

export const CATALOGUE_EXERCICES: ExerciceCatalogue[] = [
  // ── TECHNIQUE INDIVIDUELLE ─────────────────────────────────────────────────

  {
    id: 'tech-001',
    titre: 'Passes en triangle — circuit à 3',
    procede: 'exercice',
    themes: ['passe', 'controle'],
    domaine: 'technique_individuelle',
    categoriesAge: ['U10-U11', 'U12-U13', 'U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 6,
    effectifMax: 18,
    dureeMin: 10,
    dureeMax: 20,
    charges: ['Récupération', 'Modérée'],
    objectif: 'Améliorer la qualité de passe et le contrôle orienté',
    but: 'Enchaîner 20 passes consécutives sans perte de balle',
    effectifDesc: 'Groupes de 3 joueurs, 1 ballon par groupe',
    materiel: '6 plots, 1 ballon par groupe de 3',
    consignes: [
      'Placer 3 joueurs aux sommets d\'un triangle (8×8 m)',
      'Passe à 2 touches maximum',
      'Le receveur contrôle orienté vers le troisième joueur',
      'Rotation : le passeur suit sa balle',
    ],
    variantes: [
      '1 touche obligatoire',
      'Contrôle de la poitrine ou de la cuisse imposé',
      'Augmenter la distance à 15 m',
      'Intégrer un appel avant chaque réception',
    ],
    criteresReussite: [
      'Passe tendue, au pied',
      'Contrôle orienté vers l\'option suivante',
      'Déplacement immédiat après la passe',
    ],
    conseilCoach: 'Exiger que le pied d\'appui soit aligné vers le troisième joueur au moment du contrôle.',
    schema: {
      terrain: { longueur: 20, largeur: 20 },
      joueurs: [
        { x: 50, y: 10, equipe: 'A', label: '1' },
        { x: 20, y: 75, equipe: 'A', label: '2' },
        { x: 80, y: 75, equipe: 'A', label: '3' },
      ],
      ballons: [{ x: 50, y: 10 }],
      fleches: [
        { de: { x: 50, y: 10 }, vers: { x: 20, y: 75 }, type: 'passe' },
        { de: { x: 20, y: 75 }, vers: { x: 80, y: 75 }, type: 'passe' },
        { de: { x: 80, y: 75 }, vers: { x: 50, y: 10 }, type: 'passe' },
      ],
    },
    source: 'interne',
    tags: ['passe', 'contrôle', 'technique', 'triangle'],
    verified: true,
  },

  {
    id: 'tech-002',
    titre: 'Conduite de balle en slalom',
    procede: 'exercice',
    themes: ['conduite_balle', 'coordination_agilite'],
    domaine: 'technique_individuelle',
    categoriesAge: ['U8-U9', 'U10-U11', 'U12-U13', 'U14-U15'],
    effectifMin: 6,
    effectifMax: 20,
    dureeMin: 8,
    dureeMax: 15,
    charges: ['Récupération', 'Modérée'],
    objectif: 'Maîtriser la conduite à haute vitesse avec les deux pieds',
    but: 'Franchir le slalom le plus vite possible sans renverser de plots',
    effectifDesc: '2 équipes sur 2 couloirs parallèles',
    materiel: '8 plots par couloir, 1 ballon par joueur',
    consignes: [
      'Disposer 8 plots en ligne espacés de 1,5 m',
      'Conduire le ballon en slalom avec le pied intérieur et extérieur',
      'Retour en courant ballon à la main',
      'Le suivant part quand le premier a passé le dernier plot',
    ],
    variantes: [
      'Conduite pied gauche uniquement, puis pied droit uniquement',
      'Coupelle à récupérer au bout du slalom avant de revenir',
      'Ajouter un duel 1c1 à la sortie du slalom',
    ],
    criteresReussite: [
      'Le ballon reste collé au pied',
      'La tête est levée (vision du terrain)',
      'Utilisation alternée des deux pieds',
    ],
    schema: {
      terrain: { longueur: 20, largeur: 15 },
      joueurs: [
        { x: 10, y: 90, equipe: 'A' },
        { x: 30, y: 90, equipe: 'B' },
      ],
      plots: [
        { x: 10, y: 80 }, { x: 10, y: 65 }, { x: 10, y: 50 }, { x: 10, y: 35 }, { x: 10, y: 20 },
        { x: 30, y: 80 }, { x: 30, y: 65 }, { x: 30, y: 50 }, { x: 30, y: 35 }, { x: 30, y: 20 },
      ],
      ballons: [{ x: 10, y: 90 }, { x: 30, y: 90 }],
    },
    source: 'interne',
    tags: ['conduite', 'slalom', 'coordination', 'jeunes'],
    verified: true,
  },

  {
    id: 'tech-003',
    titre: 'Frappe en mouvement — crosses et finitions',
    procede: 'situation',
    themes: ['frappe', 'centre'],
    domaine: 'technique_individuelle',
    categoriesAge: ['U12-U13', 'U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 8,
    effectifMax: 16,
    dureeMin: 15,
    dureeMax: 25,
    charges: ['Modérée', 'Élevée'],
    objectif: 'Développer la frappe en première intention sur centre',
    but: 'Marquer sur la crosse du défenseur dans un grand but',
    effectifDesc: '1 centreur, 1 attaquant face au but, 1 gardien optionnel',
    materiel: 'Grand but, 6 ballons, 2 plots de couloir de centrage',
    consignes: [
      'Le centreur part de la ligne de touche à hauteur de la surface',
      'L\'attaquant démarre depuis le point de penalty',
      'Le centreur centre au sol ou mi-hauteur',
      'L\'attaquant finit en 1 touche dans le but',
      'Alterner côté droit et côté gauche',
    ],
    variantes: [
      'Ajouter un défenseur passif puis actif',
      'Le centreur peut décider de centrer ou de couper en diagonale (duel)',
      'Centre aérien avec reprise de volée',
    ],
    criteresReussite: [
      'Timing de la course de l\'attaquant (arrivée au bon moment)',
      'Contact ferme et cadré sur la frappe',
      'Le centreur frappe fort et plat au sol',
    ],
    schema: {
      terrain: { longueur: 40, largeur: 30 },
      joueurs: [
        { x: 90, y: 15, equipe: 'A', label: 'C' },
        { x: 65, y: 50, equipe: 'A', label: 'ATT' },
        { x: 95, y: 50, equipe: 'G', label: 'G' },
      ],
      buts: [{ x: 100, y: 50, taille: 'grand', orientation: 'droite' }],
      ballons: [{ x: 90, y: 15 }],
      fleches: [
        { de: { x: 90, y: 15 }, vers: { x: 85, y: 50 }, type: 'centre' as 'passe' },
        { de: { x: 65, y: 50 }, vers: { x: 85, y: 50 }, type: 'deplacement' },
        { de: { x: 85, y: 50 }, vers: { x: 100, y: 50 }, type: 'tir' },
      ],
    },
    source: 'interne',
    tags: ['frappe', 'centre', 'finition', 'mouvement'],
    verified: true,
  },

  {
    id: 'tech-004',
    titre: 'Jeu de tête — duels aériens en couloir',
    procede: 'exercice',
    themes: ['jeu_de_tete'],
    domaine: 'technique_individuelle',
    categoriesAge: ['U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 8,
    effectifMax: 20,
    dureeMin: 10,
    dureeMax: 20,
    charges: ['Modérée', 'Élevée'],
    objectif: 'Maîtriser le jeu de tête offensif et défensif',
    but: 'Remporter le maximum de duels aériens dans le couloir central',
    effectifDesc: 'Binômes (1 ATT / 1 DEF), 1 lanceur par groupe',
    materiel: '6 ballons, 4 plots',
    consignes: [
      'Le lanceur projette le ballon en hauteur dans un couloir de 5 m',
      'L\'attaquant et le défenseur entrent simultanément dans le couloir',
      'Chaque joueur essaie de dévier le ballon dans sa zone',
      '3 duels par rotation, puis changement de rôles',
    ],
    variantes: [
      'Jeu de tête piqué vers le bas uniquement',
      'Jeu de tête en course (élan avant la prise de balle)',
      'Ajouter un gardien et finir en tête cadrée',
    ],
    criteresReussite: [
      'Contact avec le front (partie dure du crâne)',
      'Regard sur le ballon jusqu\'au contact',
      'Saut bien dosé : ni trop tôt ni trop tard',
    ],
    source: 'interne',
    tags: ['tête', 'duel aérien', 'physique'],
    verified: true,
  },

  // ── TECHNICO-TACTIQUE OFFENSIF ─────────────────────────────────────────────

  {
    id: 'tto-001',
    titre: 'Rondo 4v1 — possession en losange',
    procede: 'jeu',
    themes: ['possession', 'demarquage', 'soutien'],
    domaine: 'technico_offensif',
    categoriesAge: ['U10-U11', 'U12-U13', 'U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 5,
    effectifMax: 20,
    dureeMin: 10,
    dureeMax: 20,
    charges: ['Récupération', 'Modérée'],
    objectif: 'Développer la vitesse de jeu, le soutien et le démarquage en infériorité numérique défensive',
    but: 'Réaliser 10 passes consécutives sans perte de balle',
    effectifDesc: '4 joueurs en losange + 1 chasseur au centre (groupes de 5)',
    materiel: '4 plots ou cônes, 1 ballon',
    consignes: [
      'Espace : carré de 10×10 m',
      '4 joueurs aux coins, 1 défenseur au centre',
      'Les 4 passent entre eux, le chasseur tente d\'intercepter',
      'Si le chasseur intercepte ou fait sortir le ballon, le passeur fautif devient chasseur',
      'Déplacement libre dans l\'espace pour créer des angles de passe',
    ],
    variantes: [
      '2 chasseurs (5v2)',
      '3v1 dans un triangle de 8×8 m (plus difficile)',
      'Zone de passes libres : 1 touche uniquement',
    ],
    criteresReussite: [
      'Appels de balle constants',
      'Passe avant la pression du chasseur',
      'Communication vocale entre passeurs',
    ],
    schema: {
      terrain: { longueur: 15, largeur: 15 },
      joueurs: [
        { x: 50, y: 10, equipe: 'A', label: '1' },
        { x: 10, y: 50, equipe: 'A', label: '2' },
        { x: 90, y: 50, equipe: 'A', label: '3' },
        { x: 50, y: 90, equipe: 'A', label: '4' },
        { x: 50, y: 50, equipe: 'B', label: 'D' },
      ],
      ballons: [{ x: 50, y: 10 }],
    },
    source: 'interne',
    tags: ['rondo', 'possession', 'soutien', 'passe'],
    verified: true,
  },

  {
    id: 'tto-002',
    titre: '2v1 — Démarquage et prise de profondeur',
    procede: 'situation',
    themes: ['demarquage', 'un_contre_un_offensif', 'transition_offensive'],
    domaine: 'technico_offensif',
    categoriesAge: ['U10-U11', 'U12-U13', 'U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 6,
    effectifMax: 18,
    dureeMin: 12,
    dureeMax: 20,
    charges: ['Modérée', 'Élevée'],
    objectif: 'Exploiter la supériorité numérique 2v1 en transition offensive',
    but: 'Marquer dans un mini-but ou franchir une ligne de but à 2 contre 1',
    effectifDesc: '2 attaquants vs 1 défenseur + 1 passeur lanceur',
    materiel: '2 mini-buts, 6 ballons',
    consignes: [
      'Espace de jeu : 20×15 m',
      'Le passeur relance vers les 2 attaquants qui partent simultanément',
      'Le défenseur part 2 secondes après la passe',
      'Les attaquants ont 10 secondes pour finir',
      'Rotation après chaque action',
    ],
    variantes: [
      'Défenseur actif dès la passe (départ simultané)',
      '3v2 dans un espace plus grand (30×20)',
      'Ajouter un gardien',
    ],
    criteresReussite: [
      'Le porteur de balle crée un danger immédiat pour fixer le défenseur',
      'Le partenaire démarque en profondeur ou en soutien selon le placement du défenseur',
      'Finition sans hésitation quand le 2v1 est créé',
    ],
    schema: {
      terrain: { longueur: 25, largeur: 20 },
      joueurs: [
        { x: 10, y: 50, equipe: 'A', label: 'L' },
        { x: 35, y: 30, equipe: 'A', label: 'A1' },
        { x: 35, y: 70, equipe: 'A', label: 'A2' },
        { x: 60, y: 50, equipe: 'B', label: 'D' },
      ],
      buts: [{ x: 100, y: 50, taille: 'mini', orientation: 'droite' }],
      ballons: [{ x: 10, y: 50 }],
      fleches: [
        { de: { x: 10, y: 50 }, vers: { x: 35, y: 30 }, type: 'passe' },
        { de: { x: 35, y: 30 }, vers: { x: 60, y: 30 }, type: 'conduite' },
        { de: { x: 35, y: 70 }, vers: { x: 65, y: 70 }, type: 'deplacement' },
      ],
    },
    source: 'interne',
    tags: ['2v1', 'démarquage', 'transition', 'finition'],
    verified: true,
  },

  {
    id: 'tto-003',
    titre: 'Jeu dos au but — réception et pivot',
    procede: 'exercice',
    themes: ['jeu_dos_au_but', 'soutien'],
    domaine: 'technico_offensif',
    categoriesAge: ['U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 6,
    effectifMax: 16,
    dureeMin: 12,
    dureeMax: 20,
    charges: ['Modérée'],
    objectif: 'Maîtriser la réception dos au but, le pivot et la remise',
    but: 'Conserver le ballon sous pression et orienter le jeu vers l\'avant',
    effectifDesc: '1 pivot dos au but + 1 soutien + 1 défenseur dans le dos',
    materiel: '2 mini-buts ou 4 plots, 6 ballons',
    consignes: [
      'Le pivot se positionne dos au mini-but',
      'Le partenaire lui sert la balle au sol ou mi-hauteur',
      'Le défenseur presse dans le dos du pivot',
      'Le pivot contrôle, pivote et peut : remettre, dribbler, tirer',
      'Rotation toutes les 3 actions',
    ],
    variantes: [
      '2 pivots : échange entre eux avant la finition',
      'Défenseur actif dès la passe (plus de résistance)',
      'Zones de passes supplémentaires pour développer le jeu',
    ],
    criteresReussite: [
      'Corps en bouclier face au défenseur',
      'Premier contrôle maîtrisé malgré la pression',
      'Décision rapide : retourner ou remettre',
    ],
    source: 'interne',
    tags: ['pivot', 'dos au but', 'technique', 'soutien'],
    verified: true,
  },

  {
    id: 'tto-004',
    titre: 'Permutation de postes en 4v4',
    procede: 'jeu',
    themes: ['permutation', 'animation_offensive', 'jeu_sans_ballon'],
    domaine: 'technico_offensif',
    categoriesAge: ['U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 8,
    effectifMax: 20,
    dureeMin: 15,
    dureeMax: 25,
    charges: ['Modérée', 'Élevée'],
    objectif: 'Développer la mobilité et les échanges de postes dans le jeu offensif',
    but: 'Marquer en ayant réalisé au moins 2 permutations de postes sur l\'action',
    effectifDesc: '2 équipes de 4 dans un espace réduit',
    materiel: '4 mini-buts (1 par coin), 1 ballon',
    consignes: [
      'Espace : 30×25 m, mini-but dans chaque coin',
      'Chaque équipe défend 2 buts (ceux de son côté)',
      'Un but ne compte que si au moins 2 joueurs ont changé de couloir',
      'Jeu en 2 touches maximum',
    ],
    variantes: [
      'Sans limite de touches',
      'Interdire de jouer avec le même partenaire consécutivement',
      'Ajouter un joker neutre qui joue toujours avec l\'équipe en possession',
    ],
    criteresReussite: [
      'Mouvements permanents sans ballon',
      'Les permutations créent des décalages',
      'Enchaînements rapides passe-déplacement',
    ],
    source: 'interne',
    tags: ['permutation', '4v4', 'mobilité', 'collectif'],
    verified: true,
  },

  // ── TECHNICO-TACTIQUE DÉFENSIF ─────────────────────────────────────────────

  {
    id: 'ttd-001',
    titre: '1c1 défensif — Canal central',
    procede: 'situation',
    themes: ['un_contre_un_defensif', 'marquage'],
    domaine: 'technico_defensif',
    categoriesAge: ['U12-U13', 'U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 6,
    effectifMax: 20,
    dureeMin: 12,
    dureeMax: 20,
    charges: ['Modérée', 'Élevée'],
    objectif: 'Améliorer la prise en charge défensive et l\'interception en 1c1',
    but: 'Empêcher l\'attaquant de franchir la ligne de fond ou de tirer',
    effectifDesc: '1 attaquant vs 1 défenseur par couloir, lanceur neutre',
    materiel: '2 plots délimitant le couloir (5 m de large), 6 ballons',
    consignes: [
      'Couloir de 5 m de large, 20 m de long',
      'Le lanceur sert l\'attaquant qui part vers le but',
      'Le défenseur part depuis la ligne de but et recule',
      'Objectif défenseur : orienter vers l\'extérieur et récupérer',
      'Rotation après chaque action',
    ],
    variantes: [
      'Défenseur part au signal (départ simultané attaquant)',
      'Réduire le couloir à 3 m (plus difficile pour défenseur)',
      'Ajouter un gardien',
    ],
    criteresReussite: [
      'Profil fermé (se placer entre l\'attaquant et le but)',
      'Recul mesuré : ni trop proche ni trop loin',
      'Intervention au bon moment (tacle ou blocage)',
    ],
    schema: {
      terrain: { longueur: 20, largeur: 10 },
      joueurs: [
        { x: 20, y: 50, equipe: 'A', label: 'ATT' },
        { x: 60, y: 50, equipe: 'B', label: 'DEF' },
      ],
      buts: [{ x: 100, y: 50, taille: 'mini', orientation: 'droite' }],
      ballons: [{ x: 20, y: 50 }],
      fleches: [
        { de: { x: 20, y: 50 }, vers: { x: 80, y: 50 }, type: 'conduite' },
      ],
    },
    source: 'interne',
    tags: ['1c1', 'défensif', 'marquage', 'technique'],
    verified: true,
  },

  {
    id: 'ttd-002',
    titre: 'Pressing collectif — déclenchement sur signal',
    procede: 'jeu',
    themes: ['pressing_tt', 'pressing', 'transition_defensive'],
    domaine: 'technico_defensif',
    categoriesAge: ['U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 10,
    effectifMax: 20,
    dureeMin: 15,
    dureeMax: 25,
    charges: ['Élevée'],
    objectif: 'Automatiser le déclenchement coordonné du pressing collectif',
    but: 'Récupérer le ballon en moins de 5 secondes après le signal de pressing',
    effectifDesc: '2 équipes de 5 à 6, alternance possession/pressing',
    materiel: '2 petits buts, 6 ballons, plots de zone',
    consignes: [
      'L\'équipe en possession circule le ballon librement dans son camp',
      'Au signal du coach, l\'équipe adverse déclenche le pressing coordonné',
      'Le joueur le plus proche presse, les autres couvrent les options',
      'Si récupération en < 5 s = 1 point',
      'Rotation des rôles toutes les 3 minutes',
    ],
    variantes: [
      'Pressing déclenché automatiquement sur une mauvaise passe',
      'Jeu en 1 touche pour l\'équipe en possession (accélère le jeu)',
      'Réduire l\'espace pour forcer des erreurs',
    ],
    criteresReussite: [
      'Déclenchement simultané de tout le bloc',
      'Le presseur oriente le porteur vers l\'extérieur',
      'Couverture des options de passe proches',
    ],
    source: 'interne',
    tags: ['pressing', 'collectif', 'déclenchement', 'transition défensive'],
    verified: true,
  },

  {
    id: 'ttd-003',
    titre: 'Replacement défensif — bloc bas en 4v4',
    procede: 'jeu',
    themes: ['replacement', 'animation_defensive', 'couverture'],
    domaine: 'technico_defensif',
    categoriesAge: ['U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 8,
    effectifMax: 20,
    dureeMin: 15,
    dureeMax: 25,
    charges: ['Modérée', 'Élevée'],
    objectif: 'Travailler le replacement collectif et le bloc défensif compact',
    but: 'Ne pas encaisser de but et récupérer le ballon pour contrer',
    effectifDesc: '4 défenseurs vs 4 attaquants + 2 jokers offensifs',
    materiel: 'Grand but, 8 ballons, plots de zone défensive',
    consignes: [
      'L\'équipe de 4 défend avec un bloc bas (ligne défensive haute en zone médiane)',
      'Les 4 attaquants + 2 jokers cherchent à ouvrir le bloc',
      'Les défenseurs maintiennent leur ligne et coulissent ensemble',
      'Sur récupération, contre immédiat dans les mini-buts adverses',
    ],
    variantes: [
      'Bloc moyen (pressing à mi-terrain)',
      'Défense à 5 vs 4 (supériorité défensive)',
      'Condition : le but adverse ne compte que si tout le bloc a replacé',
    ],
    criteresReussite: [
      'La ligne défensive reste compacte (pas d\'espaces entre les joueurs)',
      'Le coulissement est synchronisé',
      'Tout le monde replace immédiatement sur perte de balle',
    ],
    source: 'interne',
    tags: ['bloc bas', 'replacement', 'collectif', 'défense'],
    verified: true,
  },

  // ── TACTIQUE COLLECTIVE ────────────────────────────────────────────────────

  {
    id: 'tac-001',
    titre: 'Possession en 5v5+2 jokers — jeu de position',
    procede: 'jeu',
    themes: ['animation_offensive', 'possession'],
    domaine: 'tactique_collective',
    categoriesAge: ['U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 12,
    effectifMax: 18,
    dureeMin: 20,
    dureeMax: 35,
    charges: ['Modérée', 'Élevée'],
    objectif: 'Développer le jeu de position et la conservation collective du ballon',
    but: 'Réaliser 8 passes consécutives pour marquer 1 point',
    effectifDesc: '2 équipes de 5 + 2 jokers (jouent avec équipe en possession)',
    materiel: '8 plots (délimiter l\'espace), 1 ballon',
    consignes: [
      'Espace : 35×25 m',
      'Les jokers jouent toujours avec l\'équipe en possession (7v5)',
      'Le score de passes repart à 0 sur interception',
      'Les jokers ne peuvent pas se marquer entre eux',
    ],
    variantes: [
      'Jokers exclusivement sur les côtés (pour travailler la largeur)',
      'Obligation d\'inclure un joker à chaque série de 3 passes',
      '2 équipes de 4 + 4 jokers dans un espace plus grand',
    ],
    criteresReussite: [
      'Occupation de tout l\'espace (largeur + profondeur)',
      'Lignes de passes toujours disponibles',
      'Changement de rythme : conserver puis accélérer',
    ],
    source: 'interne',
    tags: ['possession', 'jeu de position', 'joker', 'collectif'],
    verified: true,
  },

  {
    id: 'tac-002',
    titre: 'Corner offensif — combinaisons codées',
    procede: 'situation',
    themes: ['corner', 'animation_offensive'],
    domaine: 'tactique_collective',
    categoriesAge: ['U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 8,
    effectifMax: 14,
    dureeMin: 15,
    dureeMax: 25,
    charges: ['Modérée'],
    objectif: 'Automatiser 2 à 3 combinaisons codées sur corner offensif',
    but: 'Conclure par un tir cadré ou une tête dans le grand but',
    effectifDesc: '5 attaquants (cornériste + 4 entrants) vs 3 défenseurs + gardien',
    materiel: 'Grand but, 6 ballons, plots de positionnement',
    consignes: [
      'Combinaison A : corner direct centre zone de vérité (5 m)',
      'Combinaison B : corner court vers premier appui + centre mi-hauteur',
      'Combinaison C : remontée de balle vers le milieu + frappe des 20 m',
      'Les positions de départ sont codifiées (plot de départ)',
      'Répéter chaque combinaison 5 fois puis augmenter la résistance',
    ],
    variantes: [
      '3 défenseurs actifs dès la prise du corner',
      'Créer vos propres combinaisons avec les joueurs',
    ],
    criteresReussite: [
      'Synchronisation des appels de balle',
      'Le cornériste choisit la bonne combinaison selon le signal',
      'Finition à chaque action',
    ],
    source: 'interne',
    tags: ['corner', 'combinaison', 'phase arrêtée', 'collectif'],
    verified: true,
  },

  {
    id: 'tac-003',
    titre: 'Transition rapide — 6v6 sur 2 buts',
    procede: 'jeu',
    themes: ['transition_offensive', 'transition_defensive', 'transitions'],
    domaine: 'tactique_collective',
    categoriesAge: ['U12-U13', 'U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 12,
    effectifMax: 18,
    dureeMin: 20,
    dureeMax: 30,
    charges: ['Élevée'],
    objectif: 'Développer la vitesse de transition offensive et défensive',
    but: 'Marquer dans les 6 secondes après récupération du ballon',
    effectifDesc: '2 équipes de 6 avec gardiens',
    materiel: '2 grands buts avec gardiens, 6 ballons',
    consignes: [
      'Terrain réduit : 50×35 m',
      'Dès la récupération, l\'équipe doit tirer dans les 6 secondes',
      'Sinon le coach relance pour l\'équipe adverse',
      'Pas de hors-jeu',
    ],
    variantes: [
      'Conter obligatoire avec au moins 3 joueurs',
      'Le but de transition (< 6 s) vaut 2 points',
      'Ajouter des zones interdites au pressing (pour provoquer les transitions)',
    ],
    criteresReussite: [
      'Premier contrôle orienté vers l\'avant',
      'Pas de balles jouées en retrait sur une récupération haute',
      'Les attaquants se replacent immédiatement sur perte',
    ],
    source: 'interne',
    tags: ['transition', 'vitesse', '6v6', 'contre'],
    verified: true,
  },

  // ── PHYSIQUE ───────────────────────────────────────────────────────────────

  {
    id: 'phy-001',
    titre: 'Vitesse de réaction — duels sur signal',
    procede: 'exercice',
    themes: ['vitesse_reaction', 'vitesse'],
    domaine: 'physique',
    categoriesAge: ['U10-U11', 'U12-U13', 'U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 6,
    effectifMax: 20,
    dureeMin: 10,
    dureeMax: 20,
    charges: ['Modérée', 'Élevée'],
    objectif: 'Développer la vitesse de réaction et de démarrage sur signal',
    but: 'Atteindre le ballon ou le plot en premier selon le signal du coach',
    effectifDesc: 'Binômes dos à dos, 1 ballon posé entre les 2 joueurs',
    materiel: '1 ballon par binôme, plots pour les zones',
    consignes: [
      'Les 2 joueurs sont dos à dos à 1 m l\'un de l\'autre',
      'Le ballon est posé à 3 m devant l\'un des joueurs',
      'Au signal du coach (couleur, chiffre ou sifflet), le joueur désigné doit atteindre le ballon avant son adversaire',
      'Variante : le coach désigne la direction par un geste',
      '5 séries de 5 répétitions avec 30 s de récupération',
    ],
    variantes: [
      'Signal auditif : mot "ROUGE" ou "BLEU"',
      'Signal visuel : couleur de chasubles',
      '3 joueurs (signal à 1 de 3)',
    ],
    criteresReussite: [
      'Démarrage explosif dès le signal',
      'Impulsion sur les deux jambes',
      'Bras actifs au démarrage',
    ],
    source: 'interne',
    tags: ['vitesse', 'réaction', 'duel', 'explosivité'],
    verified: true,
  },

  {
    id: 'phy-002',
    titre: 'Circuit d\'endurance avec ballon — aérobie spécifique',
    procede: 'exercice',
    themes: ['endurance'],
    domaine: 'physique',
    categoriesAge: ['U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 8,
    effectifMax: 22,
    dureeMin: 20,
    dureeMax: 35,
    charges: ['Modérée', 'Élevée'],
    objectif: 'Développer l\'endurance aérobie spécifique avec ballon',
    but: 'Maintenir l\'effort sur la durée tout en conservant la qualité technique',
    effectifDesc: 'Groupes de 3-4, rotation sur 4 ateliers',
    materiel: '4 ballons, 16 plots, 2 mini-buts',
    consignes: [
      'Atelier 1 : conduite de balle aller-retour 20 m × 4',
      'Atelier 2 : passes à 2 touches en déplacement (2 min)',
      'Atelier 3 : tirs sur mini-but après conduite (5 frappes)',
      'Atelier 4 : jeu de tête contre le mur ou partenaire (2 min)',
      'Récupération active 90 s entre les ateliers',
      'Répéter le circuit 2 fois',
    ],
    variantes: [
      'Augmenter la densité (réduire la récupération à 45 s)',
      'Intégrer des accélérations sur signal dans chaque atelier',
    ],
    criteresReussite: [
      'Maintien de la technique malgré la fatigue',
      'Fréquence cardiaque en zone aérobie (65-80%)',
      'Qualité de touche préservée en fin de circuit',
    ],
    source: 'interne',
    tags: ['endurance', 'aérobie', 'circuit', 'ballon'],
    verified: true,
  },

  {
    id: 'phy-003',
    titre: 'Coordination — parcours athlétique avec ballon',
    procede: 'exercice',
    themes: ['coordination_agilite'],
    domaine: 'physique',
    categoriesAge: ['U8-U9', 'U10-U11', 'U12-U13', 'U14-U15'],
    effectifMin: 8,
    effectifMax: 20,
    dureeMin: 12,
    dureeMax: 20,
    charges: ['Modérée'],
    objectif: 'Développer la coordination motrice générale et spécifique au football',
    but: 'Compléter le parcours en un minimum d\'erreurs',
    effectifDesc: '2 couloirs en parallèle, 1 joueur à la fois par couloir',
    materiel: 'Échelle de coordination, cerceaux, plots, 1 ballon',
    consignes: [
      'Étape 1 : traversée de l\'échelle de coordination (pieds alternés)',
      'Étape 2 : slalom en conduite entre 5 plots',
      'Étape 3 : sauts dans 3 cerceaux',
      'Étape 4 : frappe dans le mini-but',
      'Repos pendant que le partenaire passe',
    ],
    variantes: [
      'Inverser le sens du parcours',
      'Remplacer la conduite par des jonglages (5 jonglages obligatoires)',
      'Compétition entre couloirs (chronomètre)',
    ],
    criteresReussite: [
      'Enchaînement fluide des étapes',
      'Maintien du ballon pendant les sauts (cerceaux)',
      'Équilibre préservé dans l\'échelle',
    ],
    source: 'interne',
    tags: ['coordination', 'agilité', 'parcours', 'jeunes'],
    verified: true,
  },

  // ── GARDIEN DE BUT ─────────────────────────────────────────────────────────

  {
    id: 'gk-001',
    titre: 'Gardien — plongeons latéraux répétés',
    procede: 'exercice',
    themes: ['plongeon_gk', 'blocage_gk'],
    domaine: 'gardien',
    categoriesAge: ['U12-U13', 'U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 2,
    effectifMax: 4,
    dureeMin: 15,
    dureeMax: 25,
    charges: ['Modérée', 'Élevée'],
    objectif: 'Améliorer la technique de plongeon latéral et la relance immédiate',
    but: 'Capter ou dévier tous les ballons dans les angles',
    effectifDesc: '1 gardien + 1 serveur (frappeur)',
    materiel: '8 ballons, grand but, plots',
    consignes: [
      'Le frappeur est à 8 m face au but',
      'Il envoie alternativement à droite et à gauche du gardien',
      'Le gardien se relève immédiatement après chaque plongeon',
      'Séries de 6 ballons avec 60 s de récupération',
      '3 séries',
    ],
    variantes: [
      'Ajouter une balle lobée entre 2 plongeons',
      'Le frappeur décide de l\'angle (gardien réactif)',
      'Plongeon en sortie : le serveur simule une frappe croisée depuis l\'aile',
    ],
    criteresReussite: [
      'Prise d\'appui sur la jambe du côté du ballon',
      'Corps en extension, bras tendus vers le ballon',
      'Relève rapide après l\'arrêt',
    ],
    source: 'interne',
    tags: ['gardien', 'plongeon', 'arrêt', 'angles'],
    verified: true,
  },

  {
    id: 'gk-002',
    titre: 'Gardien — relance courte et longue',
    procede: 'exercice',
    themes: ['relance_gk'],
    domaine: 'gardien',
    categoriesAge: ['U12-U13', 'U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 4,
    effectifMax: 8,
    dureeMin: 12,
    dureeMax: 20,
    charges: ['Récupération', 'Modérée'],
    objectif: 'Améliorer la précision et la qualité de relance du gardien',
    but: 'Servir le partenaire désigné avec la relance choisie',
    effectifDesc: '1 gardien + 3 partenaires positionnés sur le terrain',
    materiel: 'Grand but, 6 ballons, plots de cible',
    consignes: [
      'Partenaire A : passe courte au pied (DF central à 20 m)',
      'Partenaire B : relance longue à la main (latéral à 40 m)',
      'Partenaire C : dégagement au pied (MF à 50 m)',
      'Le coach désigne la cible par signal (A/B/C)',
      'Le gardien adapte la technique selon la cible',
    ],
    variantes: [
      'Partenaires en déplacement (cible mouvante)',
      'Adversaire qui presse le gardien sur la relance courte',
      'Compter les relances réussies (cible atteinte)',
    ],
    criteresReussite: [
      'Relance courte au pied vers l\'espace devant le partenaire',
      'Relance longue : trajectoire tendue, précision acceptable',
      'Décision rapide après l\'arrêt',
    ],
    source: 'interne',
    tags: ['gardien', 'relance', 'pied', 'main', 'précision'],
    verified: true,
  },

  // ── ECHAUFFEMENTS ─────────────────────────────────────────────────────────

  {
    id: 'ech-001',
    titre: 'Mise en train — circuit jonglages et passes',
    procede: 'echauffement',
    themes: ['passe', 'conduite_balle'],
    domaine: 'technique_individuelle',
    categoriesAge: ['U8-U9', 'U10-U11', 'U12-U13', 'U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 6,
    effectifMax: 24,
    dureeMin: 10,
    dureeMax: 15,
    charges: ['Récupération'],
    objectif: 'Activer le système cardio-vasculaire et les chaînes musculaires spécifiques football',
    but: 'Arriver en pleine capacité physique et mentale pour la partie principale',
    effectifDesc: 'Tout le groupe, libre puis par paires',
    materiel: '1 ballon par joueur ou 1 pour 2',
    consignes: [
      '5 min : jonglages libres (compter ses records)',
      '3 min : passe à la main par paires (montée progressive de l\'intensité)',
      '3 min : passes au pied à 2 touches, distance croissante',
      '2 min : étirements dynamiques (mollets, ischio, adducteurs)',
      '2 min : accélérations progressives sur 20 m',
    ],
    variantes: [
      'Jonglages en défi (qui fait le plus en 1 min)',
      'Paires aléatoires tirées par le coach pour la partie passes',
    ],
    criteresReussite: [
      'Tous les joueurs actifs et concentrés',
      'Montée progressive de l\'intensité',
      'Fin de l\'échauffement : petites suées apparentes',
    ],
    source: 'interne',
    tags: ['échauffement', 'jonglage', 'passe', 'activation'],
    verified: true,
  },

  {
    id: 'ech-002',
    titre: 'Mise en train — jeu de possession ludique',
    procede: 'echauffement',
    themes: ['possession', 'demarquage'],
    domaine: 'technico_offensif',
    categoriesAge: ['U10-U11', 'U12-U13', 'U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 8,
    effectifMax: 20,
    dureeMin: 10,
    dureeMax: 15,
    charges: ['Récupération'],
    objectif: 'Échauffer le groupe en jouant et créer une bonne dynamique collective',
    but: 'Garder le ballon le plus longtemps possible en groupe',
    effectifDesc: '1 équipe de 5 vs 1 gardien du ballon, rotation',
    materiel: '1 ballon, plots pour délimiter',
    consignes: [
      'Espace : 20×15 m',
      '5 joueurs passent le ballon librement',
      '1 seul défenseur tente de récupérer',
      'Si récupération : le passeur fautif devient défenseur',
      'Intensité progressive : 50% puis 75%',
    ],
    variantes: [
      '2 défenseurs (plus de pression)',
      'Ballon ne peut pas revenir au passeur immédiat',
    ],
    criteresReussite: [
      'Tous les joueurs se déplacent constamment',
      'Communication entre passeurs',
      'Jeu simple et efficace',
    ],
    source: 'interne',
    tags: ['échauffement', 'possession', 'ludique'],
    verified: true,
  },

  // ── JEUX FINAUX ───────────────────────────────────────────────────────────

  {
    id: 'match-001',
    titre: 'Jeu final 7v7 — avec contraintes thématiques',
    procede: 'match',
    themes: ['animation_offensive', 'animation_defensive'],
    domaine: 'tactique_collective',
    categoriesAge: ['U12-U13', 'U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 14,
    effectifMax: 22,
    dureeMin: 15,
    dureeMax: 25,
    charges: ['Modérée', 'Élevée'],
    objectif: 'Ancrer les apprentissages de la séance dans un contexte de match',
    but: 'Marquer plus de buts que l\'adversaire en respectant la contrainte du jour',
    effectifDesc: '2 équipes de 7 avec gardiens',
    materiel: '2 grands buts, gardiens équipés, 6 ballons',
    consignes: [
      'Terrain adapté à l\'effectif (50×35 m pour 7v7)',
      'Contrainte du jour au choix : 3 passes min avant de tirer / but ne compte que depuis l\'aile / une passe en profondeur obligatoire...',
      'Jeu libre avec la contrainte imposée',
      'Coach arbitre et observe les objectifs de la séance',
    ],
    variantes: [
      'Suprématie (plus petite équipe a plus de gardiens ou plus de buts)',
      'Match sans gardien (apprendre à finir tôt)',
    ],
    criteresReussite: [
      'Les comportements travaillés en séance sont reproduits',
      'Esprit compétitif mais fairplay',
      'Qualité de jeu maintenue malgré l\'enjeu',
    ],
    source: 'interne',
    tags: ['match', 'jeu final', '7v7', 'contrainte'],
    verified: true,
  },

  {
    id: 'match-002',
    titre: 'Jeu final — tournoi de mini-matchs',
    procede: 'match',
    themes: ['animation_offensive', 'transitions'],
    domaine: 'tactique_collective',
    categoriesAge: ['U8-U9', 'U10-U11', 'U12-U13'],
    effectifMin: 8,
    effectifMax: 20,
    dureeMin: 15,
    dureeMax: 25,
    charges: ['Modérée'],
    objectif: 'Créer un contexte de jeu motivant pour les jeunes joueurs',
    but: 'Gagner le maximum de mini-matchs dans le tournoi',
    effectifDesc: '3 ou 4 équipes de 3-4, rotation continue',
    materiel: '4 mini-buts, 4 ballons',
    consignes: [
      '2 terrains en parallèle (15×12 m chacun)',
      'Matchs de 4 minutes, puis rotation des équipes',
      'L\'équipe qui perd ou égalise sort et affronte l\'équipe qui attend',
      'Compter les points au tableau',
    ],
    variantes: [
      'But de l\'extérieur du pied vaut 2 points',
      'Tournoi 3c3 sans gardien',
    ],
    criteresReussite: [
      'Tous les enfants jouent régulièrement',
      'Intensité et envie à chaque match',
      'Fair-play respecté',
    ],
    source: 'interne',
    tags: ['match', 'tournoi', 'jeunes', 'compétition'],
    verified: true,
  },

  // ── DUELS ─────────────────────────────────────────────────────────────────

  {
    id: 'duel-001',
    titre: 'Duel 1c1 — centre du terrain vers le but',
    procede: 'situation',
    themes: ['duels', 'un_contre_un_offensif', 'un_contre_un_defensif'],
    domaine: 'technico_offensif',
    categoriesAge: ['U12-U13', 'U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 6,
    effectifMax: 20,
    dureeMin: 12,
    dureeMax: 20,
    charges: ['Modérée', 'Élevée'],
    objectif: 'Améliorer les comportements offensifs et défensifs en duel individuel',
    but: 'L\'attaquant marque, le défenseur récupère et relance vers une cible',
    effectifDesc: 'Binômes ATT/DEF + 1 gardien + lanceur',
    materiel: 'Grand but, 6 ballons, 4 plots',
    consignes: [
      'Départ dos à dos à 2 m l\'un de l\'autre, face à leur goal respectif',
      'Le lanceur sert le ballon dans l\'espace entre eux',
      'Au signal (la balle part), chacun se retourne et part vers le ballon',
      'Celui qui gagne le ballon attaque, l\'autre défend',
      'Rotation après chaque duel',
    ],
    variantes: [
      'Départ face à face à 10 m du ballon (duel de vitesse)',
      'Ajout d\'un 2c2 (duel collectif)',
      'Zone de tir limitée (finir vite)',
    ],
    criteresReussite: [
      'ATT : feinte ou accélération pour passer le défenseur',
      'DEF : orientation rapide et profil fermé',
      'Les 2 : intensité maximale sur le duel',
    ],
    source: 'interne',
    tags: ['duel', '1c1', 'attaquant', 'défenseur', 'intensité'],
    verified: true,
  },

  // ── FINITION ──────────────────────────────────────────────────────────────

  {
    id: 'fin-001',
    titre: 'Finition — enchaînements passe-frappe',
    procede: 'situation',
    themes: ['finition', 'finition_tt', 'frappe'],
    domaine: 'technico_offensif',
    categoriesAge: ['U12-U13', 'U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 6,
    effectifMax: 16,
    dureeMin: 15,
    dureeMax: 25,
    charges: ['Modérée', 'Élevée'],
    objectif: 'Développer la qualité de finition dans différentes situations de jeu',
    but: 'Marquer dans le grand but avec le moins de touches possible',
    effectifDesc: '2 équipes en rotation sur 2 zones de finition',
    materiel: 'Grand but avec gardien, 8 ballons, 4 plots',
    consignes: [
      'Zone A (axe central 20 m) : contrôle orienté + frappe du plat',
      'Zone B (côté droit 25 m) : passe en retrait + volée',
      'Zone C (côté gauche 25 m) : conduite 5 m + frappe enroulée',
      'Chaque joueur enchaîne 3 finitions différentes',
      'Gardien actif dès la 3ème série',
    ],
    variantes: [
      'Ajouter un défenseur passif puis actif',
      'Finition en 1 touche uniquement',
      'Compétition : qui marque le plus en 5 min ?',
    ],
    criteresReussite: [
      'Frappe cadrée, puissante et vers l\'angle',
      'Tête levée avant la frappe (voir le gardien)',
      'Équilibre corporel sur la frappe',
    ],
    schema: {
      terrain: { longueur: 35, largeur: 30 },
      joueurs: [
        { x: 50, y: 50, equipe: 'A', label: 'J' },
        { x: 95, y: 50, equipe: 'G', label: 'G' },
      ],
      buts: [{ x: 100, y: 50, taille: 'grand', orientation: 'droite' }],
      ballons: [{ x: 50, y: 50 }],
      fleches: [
        { de: { x: 50, y: 50 }, vers: { x: 70, y: 50 }, type: 'conduite' },
        { de: { x: 70, y: 50 }, vers: { x: 100, y: 50 }, type: 'tir' },
      ],
    },
    source: 'interne',
    tags: ['finition', 'frappe', 'tir', 'but'],
    verified: true,
  },

  // ── MENTAL / COGNITIF ──────────────────────────────────────────────────────

  {
    id: 'cog-001',
    titre: 'Prise de décision — jeu de couleurs',
    procede: 'jeu',
    themes: ['prise_de_decision', 'passe', 'demarquage'],
    domaine: 'mental_cognitif',
    categoriesAge: ['U10-U11', 'U12-U13', 'U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 6,
    effectifMax: 18,
    dureeMin: 12,
    dureeMax: 20,
    charges: ['Modérée'],
    objectif: 'Développer la prise de décision rapide sous contrainte cognitive',
    but: 'Réaliser 10 passes aux partenaires en respectant l\'ordre de couleurs annoncé',
    effectifDesc: '3 équipes de 3 à couleurs différentes dans un carré',
    materiel: '3 jeux de chasubles de couleurs différentes, 1 ballon, plots',
    consignes: [
      'Espace : 20×20 m',
      'Le coach annonce une couleur (ex : "rouge") — le porteur doit passer à un joueur rouge',
      'Le joueur rouge annonce sa couleur suivante au moment de la réception',
      'Si erreur de couleur, le joueur fautif doit faire un tour du terrain',
      'Le jeu est continu sans interruption',
    ],
    variantes: [
      'Le coach annonce 2 couleurs (passe vers l\'une des deux)',
      'Ajouter la contrainte de 1 touche uniquement',
      'Introduire un défenseur qui ne peut chasser que sa propre couleur',
    ],
    criteresReussite: [
      'Regard immédiat sur les couleurs disponibles',
      'Passe réalisée avant que le presseur n\'arrive',
      'Communication vocale (annoncer sa couleur)',
    ],
    source: 'interne',
    tags: ['cognitif', 'décision', 'couleurs', 'vitesse de pensée'],
    verified: true,
  },

  // ── AILES / CENTRES ───────────────────────────────────────────────────────

  {
    id: 'ail-001',
    titre: 'Débordement ailier — croisement et centre',
    procede: 'situation',
    themes: ['ailes', 'centre', 'demarquage'],
    domaine: 'technico_offensif',
    categoriesAge: ['U12-U13', 'U14-U15', 'U16-U18', 'Seniors'],
    effectifMin: 8,
    effectifMax: 16,
    dureeMin: 15,
    dureeMax: 25,
    charges: ['Modérée', 'Élevée'],
    objectif: 'Automatiser le débordement ailier et le timing du centre',
    but: 'Créer un débordement et centrer pour qu\'un attaquant finisse',
    effectifDesc: '1 ailier + 1 full-back adverse + 2 attaquants en surface + gardien',
    materiel: 'Grand but avec gardien, 8 ballons, 4 plots',
    consignes: [
      'L\'ailier reçoit un ballon depuis le milieu',
      'Il doit dribbler le full-back ou accélérer dans son dos',
      'Il centre : tôt (avant le poteau) ou long (zone de vérité)',
      'Les 2 attaquants entrent en course dans la surface',
      'Alterner aile droite / aile gauche toutes les 3 actions',
    ],
    variantes: [
      'Full-back actif dès la passe (défense à haute intensité)',
      'Ailier peut décentrer et chercher un tir en diagonale',
      'Ajouter un 2c2 en surface (+ 1 défenseur supplémentaire)',
    ],
    criteresReussite: [
      'Le débordement est décisif (le full-back est passé)',
      'Le centre est précis (zone de vérité ou retrait)',
      'Les attaquants anticipent et entrent avec impulsion',
    ],
    schema: {
      terrain: { longueur: 40, largeur: 35 },
      joueurs: [
        { x: 65, y: 5, equipe: 'A', label: 'AIL' },
        { x: 75, y: 20, equipe: 'B', label: 'FB' },
        { x: 75, y: 45, equipe: 'A', label: 'A1' },
        { x: 80, y: 60, equipe: 'A', label: 'A2' },
        { x: 95, y: 50, equipe: 'G', label: 'G' },
      ],
      buts: [{ x: 100, y: 50, taille: 'grand', orientation: 'droite' }],
      ballons: [{ x: 65, y: 5 }],
      fleches: [
        { de: { x: 65, y: 5 }, vers: { x: 80, y: 5 }, type: 'conduite' },
        { de: { x: 80, y: 5 }, vers: { x: 85, y: 45 }, type: 'passe' },
        { de: { x: 75, y: 45 }, vers: { x: 88, y: 45 }, type: 'deplacement' },
      ],
    },
    source: 'interne',
    tags: ['ailier', 'débordement', 'centre', 'aile'],
    verified: true,
  },

  // ── ORGANISATION DEFENSIVE ────────────────────────────────────────────────

  {
    id: 'def-001',
    titre: 'Organisation défensive — 4-4-2 bloc moyen',
    procede: 'jeu',
    themes: ['defense', 'animation_defensive', 'replacement'],
    domaine: 'technico_defensif',
    categoriesAge: ['U16-U18', 'Seniors'],
    effectifMin: 14,
    effectifMax: 22,
    dureeMin: 20,
    dureeMax: 35,
    charges: ['Modérée', 'Élevée'],
    objectif: 'Automatiser le bloc moyen en 4-4-2 et les lignes défensives',
    but: 'Conserver l\'organisation défensive tout en pressant au bon moment',
    effectifDesc: '4-4-2 défensif (10 outfield) vs attaque à 6-8 joueurs',
    materiel: 'Grand but avec gardien, 8 ballons',
    consignes: [
      'L\'équipe défensive se place en 4-4-2 bloc moyen (milieu de terrain)',
      'L\'équipe offensive circule le ballon et cherche à ouvrir',
      'Les 2 lignes de 4 doivent coulis ser ensemble',
      'Pressing déclenché sur mauvaise passe ou contrôle manqué',
      'Sur récupération : contre rapide vers les mini-buts',
    ],
    variantes: [
      'Bloc haut (mi-terrain adverse)',
      'Zone de pression définie (si ballon sur aile droite, tous décalent à droite)',
      'Défense en 5-3-2 ou 4-5-1',
    ],
    criteresReussite: [
      'Les 2 blocs (défensifs + milieux) restent à 15 m l\'un de l\'autre maximum',
      'Le pressing est collectif, pas individuel',
      'Replacement immédiat après chaque perte du ballon',
    ],
    source: 'interne',
    tags: ['organisation défensive', '4-4-2', 'bloc', 'collectif'],
    verified: true,
  },
];
